title: "Triết Học Mỗi Ngày"
description: "Những suy nghĩ về cuộc sống, cái chết và sự tồn tại"
url: "https://canneed02.github.io"
baseurl: "/triet-hoc-moi-ngay"
permalink: /:title/
timezone: Asia/Ho_Chi_Minh

future: true

collections:
  posts:
    output: true
    permalink: /:title/
