backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "/images"

slug:
  encoding: "unicode"
  clean_accents: true

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "."
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Mô tả", name: "description", widget: "text"}
      - {label: "Nội dung", name: "body", widget: "markdown"}
      - {label: "Xuất bản", name: "published", widget: "boolean", default: true}

public_folder: ""

editor:
  preview: false
